# Setup
name:         DreamzUpAbove
tagline:      A quick journey from the beginning to the end of Universe !
baseurl:      ""
locale:       "en"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
